# Page settings
baseUrl = "elprinceserver"
title = "El Prince Roleplay Kodu Leht"
languageCode = "en-us"
theme = "hugo-elate-theme"
googleAnalytics = "G-HG23L27J15"


[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Stenuuu"
  description = ""
  email = "elprinceroleplay@gmail.com"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  
    
  [params.navigation]
    brand = "EL PRINCE ROLEPLAY"
    home = "Kodu"
    contact = "Kontakt"
    server = "Server"
    
    
    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "EL PRINCE ROLEPLAY KODULEHT"
    subtitle = 'Tere tulemast meie kodulehele.Siit saate te vajalikud infobaasid kätte.'
    description = 'HETKEL ON SERVER ARENDUSES! LIITUMINE = BAN.'              
              
 [params.about]
    enable = true
    title = "MEIE TIIM"
    

    [[params.about.item]]
      name = "Stenuuu"
      position = "Serveri Arendaja"
      description = "Hetkel on serveri arendaja "
      img = "sten.jpg"
      alt = "Person1"
      

    [[params.about.item]]
      name = "Rabbit"
      position = "Arendaja vasak poolne käsi"
      description = "Aitab leida ja lahendada probleeme"
      img = "rabbit.jpg"
      alt = "Person2"
      

    [[params.about.item]]
      name = "Kaspar Ratas"
      position = "Moderaator / Admin"
      description = "Aitab mängijaid hädast välja ja reageerib teadetele"
      img = "kaspar.jpg"
      alt = "Person3"
  
  [params.intro]

  [[params.intro.item]]
    title = "Discord"
    description = "Siin saate te discordiga liituda.Et saada whitelisti peate ootama 5 minutit"
    url = "http://discord.com/invite/ar68BQE7NP"
    button = "Liitu"
    icon = ""
    img = "img_7.jpg"
    position = "center"

  [[params.intro.item]]
    title = "Reeglid"
    description = "Enne tutvuge reeglitega! Kui neid ei jälgi ootab teid ees range puhkus"
    url = "http://docs.google.com/document/d/e/2PACX-1vRA9pB1sJPq-H_og7MYSRdUaBYSqwgse1U8wCXYq4UjnXwvVXeDDOF2WSvcoC9fTULaIffWeP2RiIhr/pub"
    button = "Loe reegleid"
    icon = ""
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Fivem Server"
    description = "Siit saate liituda FIVEM Serveriga selleks teil peab olema FIVEM programm"
    url= "fivem://connect/cfx.re/join/x966rr"
    button = "Liitu serveriga"
    icon = ""
    img = "img_10.jpg"
  [[params.intro.item]]
    title = "Teadete veebileht"
    description = "Saate teada uuendustest"
    url = "http://elprinceuuendused.onrender.com"
    button = "Uuenduste leht"
    icon = ""
    img = "img_10.jpg"
  [[params.intro.item]]
    title = "Whitelist taotlus"
    description = "Saate taodelda whitelisti"
    url = "https://forms.gle/diNZkxpZrNmtfrwFA"
    button = "Whitelist"
    icon = ""
    img = "img_10.jpg"
        

  # Counters section
  [params.counters]
    enable = false
    title = "HETKENE STAATUS"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Servereid hetkel"
      icon = "icon-briefcase"
      from = 0
      to = 1
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Arendajaid"
      icon = "icon-code"
      from = 0
      to = 4
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Võta meiega Ühendust kui teil esineb probleeme"
    
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Tallinn"],
        
        ["icon-envelope", "elprinceroleplay@gmail.com"],
        
      ]

    name = "Nimi"
    email = "Adressaat"
    phone = "Telefon*"
    message = "Jätke teave probleemist või probleemidest"
    button = "Saada kiri"

  # Footer section
[params.analytics]
  enable = true
  # Google Analytics
  [params.analytics.google]
    id = "G-HG23L27J15"
    # whether to anonymize IP
    # 是否匿名化用户 IP
    anonymizeIP = false
